# -*- coding: utf-8 -*-
"""NLU_Ass2 (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11huPUu2r0x84Ljh5ux0-eoDD_z1Yo_RV

**Note:** training_names.txt is included in the submission folder.
it needs to be uploaded in the same directory as the notebook before running.

## Dataset Generation

Loading a dataset of 1000 Indian names generated using an LLM.

The dataset includes realistic Indian names such as short names like Ram, Sita, Om, Raj as well as longer names such as Devansh, Siddharth, and Ananya.

Names are loaded from training_names.txt, with one name per line. This file serves as the training dataset for the character-level sequence models.
"""

# Loading the LLM-generated dataset from file

with open("training_names.txt", "r") as f:
    names = f.read().splitlines()
    names = [n.strip() for n in names if n.strip()]

print(f"{len(names)} names have been loaded")

# Printing sample names
print(names[:20])

"""## Creating Character Vocabulary

Extracting all unique characters appearing in the dataset.

Adding a special character '.' to represent the end of a name during sequence modeling.
"""

# Creating character vocabulary from dataset
characters = sorted(list(set("".join(names))))

# Adding end-of-sequence character to mark the end of each name
characters.append(".")

# Creating mapping dictionaries: character <-> index
char_to_idx = {ch: i for i, ch in enumerate(characters)}
idx_to_char = {i: ch for ch, i in char_to_idx.items()}

vocab_size = len(characters)

print("Vocabulary size:", vocab_size)
print(characters)

"""## Converting Names into Training Sequences

Transforming each name into input-output character sequences.

Using the current character as input and predicting the next character as the target.
"""

# Creating training sequences
encoded_names = []

for name in names:

    # Appending EOS token to each name so model learns when to stop
    name = name + "."

    # Converting each character to its integer index
    encoded = [char_to_idx[ch] for ch in name]

    encoded_names.append(encoded)

print("Example encoded name:", encoded_names[0])

"""## Implementing Vanilla Recurrent Neural Network

Implementing a character-level Vanilla RNN for learning sequential patterns in Indian names.

Using the current character as input and predicting the next character in the sequence.

Training the model to generate realistic names by learning character transitions from the dataset.
"""

# Creating input and target sequences from encoded names
inputs = []
targets = []

for seq in encoded_names:

    # All characters except the last one are inputs
    inputs.append(seq[:-1])

    # All characters except the first one are targets (shifted by 1)
    targets.append(seq[1:])

print("Example input:", inputs[0])
print("Example target:", targets[0])

import torch
from torch.nn.utils.rnn import pad_sequence

# Converting sequences to tensors
input_tensors = [torch.tensor(seq, dtype=torch.long) for seq in inputs]
target_tensors = [torch.tensor(seq, dtype=torch.long) for seq in targets]

# Padding all sequences to the same length (length of the longest name)
# padding_value=0 is the index of space character; ignored in loss via ignore_index=0
inputs_padded = pad_sequence(input_tensors, batch_first=True, padding_value=0)
targets_padded = pad_sequence(target_tensors, batch_first=True, padding_value=0)

print("Input tensor shape:", inputs_padded.shape)
print("Target tensor shape:", targets_padded.shape)

import torch.nn as nn
import torch.optim as optim

class VanillaRNN(nn.Module):

    def __init__(self, vocab_size, hidden_size):
        super(VanillaRNN, self).__init__()

        # Embedding layer: maps each character index to a dense vector
        self.embedding = nn.Embedding(vocab_size, hidden_size)

        # Recurrent layer: processes the sequence step by step
        self.rnn = nn.RNN(hidden_size, hidden_size, batch_first=True)

        # Output layer: projects hidden state to vocabulary logits
        self.fc = nn.Linear(hidden_size, vocab_size)

    def forward(self, x):

        # Converting character indices into dense embedding vectors
        x = self.embedding(x)

        # Passing embeddings through the RNN layer
        out, _ = self.rnn(x)

        # Projecting RNN output to vocabulary size for next-char prediction
        out = self.fc(out)

        return out

# Defining hyperparameters
hidden_size = 128
learning_rate = 0.003
epochs = 40

# Initializing Vanilla RNN model
model = VanillaRNN(vocab_size, hidden_size)

# Cross-entropy loss; ignore_index=0 skips padded positions during loss computation
criterion = nn.CrossEntropyLoss(ignore_index=0)

# Adam optimizer for adaptive learning
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

print(model)

# Counting total trainable parameters in the RNN model
total_params_rnn = sum(p.numel() for p in model.parameters() if p.requires_grad)
print("RNN Total Trainable Parameters:", total_params_rnn)

for epoch in range(epochs):

    # Clearing gradients from previous step
    optimizer.zero_grad()

    # Forward pass: get predictions for all characters in all names
    outputs = model(inputs_padded)

    # Flattening: (batch, seq_len, vocab) -> (batch*seq_len, vocab)
    outputs = outputs.reshape(-1, vocab_size)
    targets_flat = targets_padded.reshape(-1)

    # Computing cross-entropy loss (padded positions are ignored)
    loss = criterion(outputs, targets_flat)

    # Backpropagation: computing gradients
    loss.backward()

    # Updating model weights
    optimizer.step()

    print(f"Epoch {epoch+1}/{epochs}, Loss: {loss.item():.4f}")

"""## Generating Names Using the Trained RNN

Generating new Indian names by sampling characters sequentially from the trained Vanilla RNN.

Starting from a random uppercase letter and repeatedly predicting the next character until the end-of-sequence token is produced.
"""

import torch
import torch.nn.functional as F
import random

def generate_full_name(model, temperature=0.7, max_length=25):

    model.eval()

    # Starting with a random uppercase letter (realistic name start)
    # Previously used any alphabet character (including lowercase),
    # now restricted to uppercase for proper name formatting
    start_char = random.choice([c for c in char_to_idx if c.isupper()])

    name = start_char
    input_seq = torch.tensor([[char_to_idx[start_char]]], dtype=torch.long)

    # Flag to track whether the space (first/last name boundary) has been inserted
    space_added = False

    for _ in range(max_length):

        with torch.no_grad():
            output = model(input_seq)

        # Applying temperature scaling before softmax
        logits = output[0, -1] / temperature
        probs = F.softmax(logits, dim=0)

        # Sampling next character from probability distribution
        char_idx = torch.multinomial(probs, 1).item()
        next_char = idx_to_char[char_idx]

        # Forcing a space after first name (len > 4) to ensure full name structure
        if not space_added and len(name) > 4:
            next_char = " "
            space_added = True

        # Stopping when EOS token is generated
        if next_char == ".":
            break

        name += next_char

        # Using the space index explicitly to avoid KeyError
        next_tensor = torch.tensor([[char_to_idx.get(next_char, char_idx)]])
        input_seq = torch.cat((input_seq, next_tensor), dim=1)

    return name.strip()

"""## Filtering Generated Names

Generating multiple names from the trained model and filtering out very short or incomplete outputs.

Keeping names that resemble realistic full-name structures.
"""

rnn_generated_raw = []

for _ in range(200):
    name = generate_full_name(model)
    rnn_generated_raw.append(name)

# Filtering to keep only realistic full name structures
clean_rnn = []
for name in rnn_generated_raw:
    parts = name.split()
    if len(parts) == 2 and 3 <= len(parts[0]) <= 10 and 3 <= len(parts[1]) <= 12 and len(name) > 6:
        clean_rnn.append(name)

# Removing duplicates
clean_rnn = list(set(clean_rnn))

print("Sample generated names (RNN):")
clean_rnn[:30]

"""## Quantitative Evaluation — Vanilla RNN

Evaluating the generated names using two quantitative metrics.

**Novelty Rate** measures the percentage of generated names that do not appear in the training dataset.

**Diversity** measures how many unique names are produced relative to the total number of generated names.
"""

# Generating a larger set of names for evaluation
rnn_eval_raw = [generate_full_name(model) for _ in range(500)]

rnn_eval = []
for name in rnn_eval_raw:
    parts = name.split()
    if len(parts) == 2 and 3 <= len(parts[0]) <= 10 and 3 <= len(parts[1]) <= 12 and len(name) > 6:
        rnn_eval.append(name)

print(f"Valid names after filtering: {len(rnn_eval)} out of {len(rnn_eval_raw)}")
print("Sample:", rnn_eval[:20])

"""## Computing Novelty Rate — RNN

Calculating the percentage of generated names that are not present in the training dataset.

Higher novelty indicates that the model is producing new names rather than memorizing the training data.
"""

# Converting training names to a set for O(1) lookup
training_set = set(names)

# Counting names not present in training dataset
novel_rnn = [name for name in rnn_eval if name not in training_set]

novelty_rate_rnn = len(novel_rnn) / len(rnn_eval)

print("RNN Novelty Rate:", novelty_rate_rnn)

"""## Computing Diversity — RNN

Measuring the diversity of generated names.

Diversity is calculated as the ratio of unique generated names to the total number of generated names.
"""

# Unique names divided by total generated names
diversity_rnn = len(set(rnn_eval)) / len(rnn_eval)

print("RNN Diversity:", diversity_rnn)

"""## Observations — Vanilla RNN

The Vanilla RNN learns character-level transitions in Indian names. Novelty 1.0 shows the model generates new combinations rather than memorizing. Diversity reflects how varied the outputs are across samples.

## Model 2: Bidirectional Long Short-Term Memory (BLSTM)

Implementing a Bidirectional LSTM for character-level name generation.

The main difference from the Vanilla RNN is that BLSTM runs two LSTM layers — one reads left-to-right, the other right-to-left. Their hidden states are concatenated at each step, giving the model access to both past and future character context during training.

LSTMs also solve the vanishing gradient problem that affects vanilla RNNs, thanks to gating mechanisms (input gate, forget gate, output gate) that control what information flows through the cell state.

Architecture used: Embedding → BiLSTM → Linear output layer
"""

import torch
import torch.nn as nn
import torch.optim as optim

# Defining BLSTM model for character-level sequence prediction
class BLSTMModel(nn.Module):

    def __init__(self, vocab_size, hidden_size):
        super(BLSTMModel, self).__init__()

        # Embedding layer: maps character indices to dense vectors
        self.embedding = nn.Embedding(vocab_size, hidden_size)

        # Bidirectional LSTM: processes sequence in both directions
        self.blstm = nn.LSTM(
            input_size=hidden_size,
            hidden_size=hidden_size,
            batch_first=True,
            bidirectional=True
        )

        # Output layer: hidden_size*2 because BiLSTM concatenates both directions
        self.fc = nn.Linear(hidden_size * 2, vocab_size)

    def forward(self, x):

        # Embedding lookup
        x = self.embedding(x)

        # Passing sequence through bidirectional LSTM
        out, _ = self.blstm(x)

        # Projecting concatenated hidden states to vocabulary logits
        out = self.fc(out)

        return out

hidden_size = 128
learning_rate = 0.003
epochs = 20

# Creating BLSTM model instance
blstm_model = BLSTMModel(vocab_size, hidden_size)

# Loss function ignoring padded positions
criterion = nn.CrossEntropyLoss(ignore_index=0)

# Adam optimizer
optimizer = optim.Adam(blstm_model.parameters(), lr=learning_rate)

print(blstm_model)

"""## Trainable Parameters — BLSTM
Reporting the total number of trainable parameters in the BLSTM model.
"""

# Counting total trainable parameters in the BLSTM model
total_params_blstm = sum(p.numel() for p in blstm_model.parameters() if p.requires_grad)
print("BLSTM Total Trainable Parameters:", total_params_blstm)

for epoch in range(epochs):

    # Clearing gradients from previous step
    optimizer.zero_grad()

    # Forward pass through BLSTM
    outputs = blstm_model(inputs_padded)

    # Flattening for loss computation
    outputs = outputs.reshape(-1, vocab_size)
    targets_flat = targets_padded.reshape(-1)

    # Calculating cross-entropy loss
    loss = criterion(outputs, targets_flat)

    # Backpropagation
    loss.backward()

    # Updating model parameters
    optimizer.step()

    print(f"Epoch {epoch+1}/{epochs}, Loss: {loss.item():.4f}")

import torch
import torch.nn.functional as F
import random

def generate_full_name_blstm(model, temperature=0.7, max_length=20):

    model.eval()

    # Starting from a random uppercase letter — model must generate everything
    # (no leaking of real training first names as seed)
    start_char = random.choice([c for c in char_to_idx if c.isupper()])

    name = start_char
    input_seq = torch.tensor([[char_to_idx[start_char]]], dtype=torch.long)

    # Flag for first/last name boundary
    space_added = False

    for _ in range(max_length):

        with torch.no_grad():
            output = model(input_seq)

        # Temperature-scaled softmax for controlled randomness
        logits = output[0, -1] / temperature
        probs = F.softmax(logits, dim=0)

        # Sampling next character
        char_idx = torch.multinomial(probs, 1).item()
        next_char = idx_to_char[char_idx]

        # Forcing space after first name (len > 4), consistent with RNN
        if not space_added and len(name) > 4:
            next_char = " "
            space_added = True

        # Stopping at EOS token
        if next_char == ".":
            break

        name += next_char

        # Feeding next character back into the model
        next_tensor = torch.tensor([[char_to_idx.get(next_char, char_idx)]])
        input_seq = torch.cat((input_seq, next_tensor), dim=1)

    return name.strip()

generated_blstm = [generate_full_name_blstm(blstm_model) for _ in range(200)]

# Filtering to keep only realistic full-name structures
clean_blstm = []

for name in generated_blstm:
    parts = name.split()
    if len(parts) == 2 and 3 <= len(parts[0]) <= 10 and 3 <= len(parts[1]) <= 12:
        clean_blstm.append(name)

# Removing duplicates from display sample
clean_blstm = list(set(clean_blstm))

print("Sample generated names (BLSTM):")
clean_blstm[:30]

"""## Quantitative Evaluation — BLSTM

Evaluating the generated names using two quantitative metrics.

**Novelty Rate** measures the percentage of generated names that do not appear in the training dataset.

**Diversity** measures how many unique names are produced relative to the total number of generated names.
"""

# Generating a larger set of 500 names for evaluation (separate from display sample)
blstm_eval_raw = [generate_full_name_blstm(blstm_model) for _ in range(500)]

# Applying same filter for consistent evaluation
blstm_eval = []
for name in blstm_eval_raw:
    parts = name.split()
    if len(parts) == 2 and 3 <= len(parts[0]) <= 10 and 3 <= len(parts[1]) <= 12 and len(name) > 6:
        blstm_eval.append(name)

print(f"Valid names after filtering: {len(blstm_eval)} out of {len(blstm_eval_raw)}")

"""## Computing Novelty Rate — BLSTM

Calculating the percentage of generated names that are not present in the training dataset.

"""

# Converting training dataset into a set for quick lookup
training_set = set(names)

# Counting names that are not in training data (evaluated on filtered list)
novel_names_blstm = [n for n in blstm_eval if n not in training_set]
novelty_blstm = len(novel_names_blstm) / len(blstm_eval)

print("BLSTM Novelty Rate:", novelty_blstm)

"""## Computing Diversity — BLSTM

Diversity is calculated as the ratio of unique generated names to the total number of generated names.
"""

# Unique names divided by total filtered generated names
diversity_blstm = len(set(blstm_eval)) / len(blstm_eval)

print("BLSTM Diversity:", diversity_blstm)

"""## Observations — BLSTM

The BLSTM achieves lower training loss but produces less coherent names during generation. This is because BLSTMs are trained with access to future context in both directions, but generation is inherently left to right, the backward pass cannot be used at inference time. This architectural mismatch is a known limitation of using BLSTMs for autoregressive generation tasks.

## Model 3: RNN with Attention

Implementing a character level Recurrent Neural Network with a basic attention mechanism.

The attention mechanism allows the model to focus on relevant parts of the sequence when predicting the next character. This helps the model capture stronger dependencies between characters in names compared to a simple RNN.
"""

class AttentionRNN(nn.Module):

    def __init__(self, vocab_size, hidden_size):
        super(AttentionRNN, self).__init__()

        self.hidden_size = hidden_size

        # Embedding layer
        self.embedding = nn.Embedding(vocab_size, hidden_size)

        # Recurrent layer
        self.rnn = nn.RNN(hidden_size, hidden_size, batch_first=True)

        # Attention scoring layer: hidden_size → 1 scalar per timestep
        self.attn = nn.Linear(hidden_size, 1)

        # Output layer: takes hidden + context (both size hidden_size)
        self.fc = nn.Linear(hidden_size, vocab_size)

    def forward(self, x):

        # Embedding lookup
        x = self.embedding(x)

        # RNN forward pass — get hidden state at every timestep
        rnn_out, _ = self.rnn(x)
        # rnn_out shape: (batch, seq_len, hidden_size)

        # Score each hidden state with a linear layer → scalar per timestep
        attn_scores = self.attn(rnn_out)
        # attn_scores shape: (batch, seq_len, 1)

        # Softmax over sequence length to get attention weights
        attn_weights = torch.softmax(attn_scores, dim=1)
        # attn_weights shape: (batch, seq_len, 1)

        # Weighted sum of all hidden states = context vector
        context = (attn_weights * rnn_out).sum(dim=1, keepdim=True)
        # context shape: (batch, 1, hidden_size)

        # Expand context to match seq_len so it can be added to each timestep
        context = context.expand_as(rnn_out)

        # Combine RNN hidden state with attended context
        out = rnn_out + context

        out = self.fc(out)

        return out

"""## Initializing the Attention RNN

Defining model hyperparameters and initializing the attention-based RNN model.
"""

hidden_size = 128
learning_rate = 0.003
epochs = 40

# Initializing the attention-based RNN model
attention_model = AttentionRNN(vocab_size, hidden_size)

# Cross-entropy loss ignoring padding
criterion = nn.CrossEntropyLoss(ignore_index=0)

# Adam optimizer
optimizer = torch.optim.Adam(attention_model.parameters(), lr=learning_rate)

print(attention_model)

"""## Trainable Parameters — Attention RNN
Reporting the total number of trainable parameters in the Attention RNN model.
"""

# Counting total trainable parameters in the Attention RNN model
total_params_attention = sum(p.numel() for p in attention_model.parameters() if p.requires_grad)
print("Attention RNN Total Trainable Parameters:", total_params_attention)

"""## Training the Attention RNN

Training the model using the same character-level sequences used for the previous models.
"""

for epoch in range(epochs):

    # Clearing gradients
    optimizer.zero_grad()

    # Forward pass through attention RNN
    outputs = attention_model(inputs_padded)

    # Flattening for loss
    outputs = outputs.reshape(-1, vocab_size)
    targets_flat = targets_padded.reshape(-1)

    # Computing loss
    loss = criterion(outputs, targets_flat)

    # Backpropagation
    loss.backward()

    # Weight update
    optimizer.step()

    print(f"Epoch {epoch+1}/{epochs}, Loss: {loss.item():.4f}")

"""## Generating Names Using Attention RNN

Generating names using the trained attention-based RNN model.
"""

import torch
import torch.nn.functional as F
import random

def generate_name_attention(model, temperature=0.8, max_length=25):

    model.eval()

    start_char = random.choice([c for c in char_to_idx if c.isupper()])
    name = start_char
    input_seq = torch.tensor([[char_to_idx[start_char]]], dtype=torch.long)
    space_added = False

    for _ in range(max_length):

        with torch.no_grad():
            output = model(input_seq)

        logits = output[0, -1] / temperature
        probs = F.softmax(logits, dim=0)

        char_idx = torch.multinomial(probs, 1).item()
        next_char = idx_to_char[char_idx]

        if not space_added and len(name) > 4:
            next_char = " "
            space_added = True

        if next_char == ".":
            break

        # After space, force next character to be uppercase (start of last name)
        if name.endswith(" ") and next_char.isalpha():
            next_char = next_char.upper()

        # After first character of each word, force lowercase
        # to avoid random capitals mid-word
        if not name.endswith(" ") and len(name) > 1 and next_char.isalpha():
            # Only first char of each word should be upper
            last_word = name.split()[-1] if name.split() else name
            if len(last_word) > 0:
                next_char = next_char.lower()

        name += next_char

        next_tensor = torch.tensor([[char_to_idx.get(next_char, char_idx)]])
        input_seq = torch.cat((input_seq, next_tensor), dim=1)

    return ' '.join(word.capitalize() for word in name.strip().split())

# Generating 200 names from the attention model
generated_attention = [generate_name_attention(attention_model) for _ in range(200)]

# Filtering to realistic full-name structures
clean_attention = []

for name in generated_attention:
    parts = name.split()
    if len(parts) == 2 and 3 <= len(parts[0]) <= 10 and 3 <= len(parts[1]) <= 12:
        clean_attention.append(name)

# Removing duplicates
clean_attention = list(set(clean_attention))

print("Sample generated names (Attention RNN):")
clean_attention[:30]

"""## Quantitative Evaluation — Attention RNN

Evaluating the generated names using two quantitative metrics.

**Novelty Rate** measures the percentage of generated names that do not appear in the training dataset.

**Diversity** measures how many unique names are produced relative to the total number of generated names.

"""

# Generating a larger set of 500 names for evaluation (separate from display sample)
attention_eval_raw = [generate_name_attention(attention_model) for _ in range(500)]

# Applying same filter for consistent evaluation
attention_eval = []
for name in attention_eval_raw:
    parts = name.split()
    if len(parts) == 2 and 3 <= len(parts[0]) <= 10 and 3 <= len(parts[1]) <= 12 and len(name) > 6:
        attention_eval.append(name)

print(f"Valid names after filtering: {len(attention_eval)} out of {len(attention_eval_raw)}")

"""## Computing Novelty Rate — Attention RNN

Calculating the percentage of generated names that are not present in the training dataset.

"""

# Converting training names to a set for O(1) lookup
training_set = set(names)

# Counting names not present in training dataset
novel_attention = [n for n in attention_eval if n not in training_set]
novelty_attention = len(novel_attention) / len(attention_eval) if attention_eval else 0

print("Attention RNN Novelty Rate:", novelty_attention)

"""## Computing Diversity — Attention RNN

Diversity is calculated as the ratio of unique generated names to the total number of generated names.
"""

# Unique names divided by total filtered generated names
diversity_attention = len(set(attention_eval)) / len(attention_eval) if attention_eval else 0

print("Attention RNN Diversity:", diversity_attention)

"""## Observations — Attention RNN

The Attention RNN produces the most recognisable Indian phonetic patterns among the three models. Common failure modes include repeated consonants and overly long surnames, suggesting the model occasionally fails to terminate sequences appropriately.

"""

print("=" * 55)
print(f"{'Model':<20} {'Novelty Rate':>15} {'Diversity':>15}")
print("=" * 55)
print(f"{'Vanilla RNN':<20} {novelty_rate_rnn:>15.4f} {diversity_rnn:>15.4f}")
print(f"{'BLSTM':<20} {novelty_blstm:>15.4f} {diversity_blstm:>15.4f}")
print(f"{'Attention RNN':<20} {novelty_attention:>15.4f} {diversity_attention:>15.4f}")
print("=" * 55)

"""## Task 2: Quantitative Evaluation — Cross-Model Comparison

The table above is a summary of the Novelty Rate and Diversity scores of all the three models tested on 500 generated names (filtered by valid full-name structure).

**Novelty Rate**  is a percentage of generated names which are not found in the training set. A score of 1.0 implies that all the generated names are new and the model is not just remembering training data.

**Diversity** is the number of distinct generated names/ the number of generated names. A score near to 1.0 indicates that the model is not repeated frequently and yields diverse output.

### Results Discussion

**Vanilla RNN** has high novelty as generation at the character level seldom replicates the training names to the exact. Diversity is medium and the model has been trained on typical Indian character changes but occasionally the similarities are merged, particularly in case of surnames.

**BLSTM** achieves perfect or near-perfect novelty because its garbled outputs almost never match any training name exactly. However, this high novelty is not a sign of quality instead it reflects incoherence rather than creativity. Diversity is also high for the same reason: the model produces random character combinations that are all different from each other.

**Attention RNN**  has great novelty and the most successful diversity of the three models. The attention mechanism enables the model to give attention to the relevant previous characters, which generate more diverse and phonetically regular outputs than the Vanilla RNN.

### Key Observation
The raw novelty and diversity scores are not always accurate, the BLSTM scores high on both of them, although it generates the lowest quality names. Task 3 is thus necessary to conduct a qualitative analysis in order to assess model performance appropriately.

## Task 3: Qualitative Analysis

This section discusses the realism of generated names, representative samples from each model, and common failure modes observed during generation.

---

### Model 1: Vanilla RNN

**Realism:**
 Vanilla RNN produces recognisable phonetic names with Indian patterns. Majority of the first names are typical Indian names that are well constructed. In other cases, surnames may contain components of several training surnames, indicating that the model has perfected character-level changing but not word level structure.

**Representative Samples:**
The outputs include names like Rohan Sharma, Arjun Patel, and Deepa Jha that sound like real Indian full names. Names like Ramri Patil or Latal Gupta show that the model has learned parts of names but sometimes puts them together wrong.

**Common Failure Modes:**
- Truncated first names that are cut off before completing a recognisable name (e.g., Ramr, Vivaa)
- Surnames ending with extra characters (e.g., Mishran, Prasay)
- Occasional lowercase starts after the space separator

**Reason:**
 The Vanilla RNN carries information of preceding characters with one hidden state. This concealed manner is a fixed-size list that diminishes information of former characters as the sequence expands due to the need to condense the history of the sequence as a whole. It is referred to as the vanishing gradient problem, in which the gradients get worse as a sequence of backpropagation takes place, and it is difficult to have the model identify pattern of characters that are far apart. Because of this, the model does a good job of learning short-range character transitions but finds it difficult to maintain the structure of a full name, which results in shortened first names and improperly formed surnames.

---

### Model 2: Bidirectional LSTM (BLSTM)

**Realism:**
Out of the three models, the BLSTM achieves the lowest training loss while producing the least coherent names. Outputs frequently contain non-Indian phonetic combinations, random capital letters in the middle of words, and structurally incorrect character sequences.


**Representative Samples:**
Outputs such as XIBin MMllay, UWwDj Gurjee, and Dxmen Donen show the model has not learned coherent name patterns. Occasional outputs like Gayud Sulkavev or Lytaa Dikkityyan show partial Indian phonetic fragments but are still not realistic names.

**Common Failure Modes:**
- Random uppercase letters mid-word (e.g., XIBin, MMllay, UWwDj)
- Non-Indian character combinations with no phonetic resemblance to Indian names
- Structurally invalid patterns with repeated characters or consonant clusters

**Reason for Poor Generation:**
Every position sees both past and future characters because BiLSTMs are trained with bidirectional context. Because generation is left-to-right at inference, the backward pass is not possible. The reason for this disparity is that the model was optimised for a different task than the one it was asked to complete during generation.

---

### Model 3: RNN with Attention

**Realism:**
Out of the three models, the Attention RNN generates the most identifiable Indian phonetic patterns. The model produces outputs that are more varied and coherent than both the Vanilla RNN and the BLSTM because the attention mechanism enables the model to concentrate on pertinent prior characters when predicting the subsequent character.

**Representative Samples:**
The model has learned Indian phonetic patterns because it can output things like Bosha Shati, Basaman Jashi, and Omila Daisinishni. Most of the time, first names are real. Last names are longer and sometimes add extra characters, but they still follow Indian phonetic rules.

**Common Failure Modes:**
- Repeated consonants in first names (e.g., Raddd, Bandd, Pindd) — the model occasionally gets stuck in a character loop
- Overly long surnames (e.g., Suagurureri, Rediradara, Daisinishni) — the model fails to produce the EOS token at the right point
- Occasional non-Indian first names (e.g., Iupon, Raboo) due to starting from a random uppercase letter that the model has not learned to associate with Indian name patterns

**Reason:**
The model is still constrained by the underlying RNN, which has the same vanishing gradient problem as the Vanilla RNN, even though the attention mechanism helps it concentrate on pertinent prior characters. Furthermore, a simple global attention mechanism is employed here, which simultaneously computes a weighted sum over all prior hidden states. Instead of concentrating sharply on the most pertinent characters during generation, the attention weights may become diffuse and spread over too many timesteps as the sequence gets longer.

---

### Overall Comparison

| Model | Realism | Failure Mode |
|---|---|---|
| Vanilla RNN | Moderate — recognisable fragments, occasional truncation | Truncated names, mixed surname fragments |
| BLSTM | Poor — largely incoherent due to bidirectional training vs left-to-right generation mismatch | Random capitalisation, non-Indian phonetics |
| Attention RNN | Best — most phonetically consistent Indian name patterns | Repeated consonants, overly long surnames |

The Attention RNN is the strongest model for this task. The BLSTM, despite its architectural sophistication, is poorly suited for autoregressive character-level generation. The Vanilla RNN serves as a reasonable baseline but is outperformed by the attention mechanism in terms of output quality.
"""